/**
 * Helper class that scans the local file system
 * <p>
 * Note: DO NOT EDIT THIS FILE.
 * ***********************************************************************
 * Computer Science 102: Data Structures
 * New York University, Fall 2013,
 * Lecturers: Eric Koskinen and Daniel Schwartz-Narbonne
 * ***********************************************************************
 *
 * @author      Eric Koskinen       <ejk@cs.nyu.edu>
 * @version     $Revision$
 * @since       2013-10-30
 */
import java.io.File;
import java.io.IOException;
import java.util.HashMap;

public class Loader {
    private HashMap<String,File> hm = null;
    private boolean DEBUG = false;
    
    public HashMap<String,File> load(String dirName) throws IOException {
	File dir = new File(dirName);
	if(!dir.isDirectory())
	    throw new IOException("Loader: " + dirName + " is not a dir");
	if (hm != null) System.out.println("Warning: reloading.\n");
	hm = new HashMap<String,File>(20);
	if (DEBUG) System.out.println("Loading " + dirName + "...");
	build("CWD/"+dirName, dir);
	return hm;
    }

    public void build(String prefix, File dir) {
	//try {
	    File[] files = dir.listFiles();
	    for (File file : files) {
		if (file.isDirectory()) {
		    if (DEBUG) System.out.println("directory: " + prefix+file.getName());
		    build(prefix+"/"+file.getName(),file);
		} else {
		    if (DEBUG) System.out.println("     file: " + prefix+file.getName());
		    hm.put(prefix+"/"+file.getName(),file);
		}
	    }
	    //	} catch (IOException e) {
	    //e.printStackTrace();
	    //}
    }
}