/**
 * Queue interface
 * <p>
 * Note: DO NOT EDIT THIS FILE.
 * ***********************************************************************
 * Computer Science 102: Data Structures
 * New York University, Fall 2013,
 * Lecturers: Eric Koskinen and Daniel Schwartz-Narbonne
 * ***********************************************************************
 *
 * @author      Eric Koskinen       <ejk@cs.nyu.edu>
 * @version     $Revision$
 * @since       2013-09-01
 */

public interface Queue<E> extends Collection<E> {
    // Basic operations
    int size();
    void enqueue(E element);
    E dequeue() throws InvalidOperationException;    
    boolean isEmpty();

    // Output operations
    String toString();
    void PrettyPrint();
}